/**
 * Growth/SEO config integrity checks.
 * Usage: node scripts/seo-assert.js
 *
 * Fails on:
 *  - duplicate ids/slugs
 *  - chainsTo → unknown tool id
 *  - missing primaryInputId in target tool HTML (when set)
 *  - missing map/toField destination id in target HTML
 *  - missing content-site tool page
 *  - registry files out of date vs emit (if registries exist)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { tools, getToolById } = require('./toolsConfig');

const root = path.join(__dirname, '..');
const toolsDir = path.join(root, 'content-site', 'tools');

let errors = 0;
let warnings = 0;

function fail(msg) {
  console.error('ERROR:', msg);
  errors++;
}

function warn(msg) {
  console.warn('WARN:', msg);
  warnings++;
}

function htmlHasId(html, id) {
  if (!id) return true;
  // id="foo" or id='foo'
  const re = new RegExp('id\\s*=\\s*["\']' + id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '["\']', 'i');
  return re.test(html);
}

const slugs = new Map();
const ids = new Set();

for (const t of tools) {
  if (ids.has(t.id)) fail('duplicate tool id: ' + t.id);
  ids.add(t.id);

  if (slugs.has(t.slug)) {
    fail('duplicate slug: ' + t.slug + ' → ' + t.id + ' and ' + slugs.get(t.slug));
  }
  slugs.set(t.slug, t.id);

  const indexPath = path.join(toolsDir, t.slug, 'index.html');
  if (!fs.existsSync(indexPath)) {
    warn('missing page ' + path.relative(root, indexPath));
    continue;
  }
  const html = fs.readFileSync(indexPath, 'utf8');

  if (t.primaryInputId && !htmlHasId(html, t.primaryInputId)) {
    fail(t.id + ': primaryInputId "' + t.primaryInputId + '" not found in index.html');
  }
  if (t.primaryOutputId && !htmlHasId(html, t.primaryOutputId)) {
    fail(t.id + ': primaryOutputId "' + t.primaryOutputId + '" not found in index.html');
  }

  for (const chain of t.chainsTo || []) {
    const target = getToolById(chain.id);
    if (!target) {
      fail(t.id + ': chainsTo unknown id ' + chain.id);
      continue;
    }
    const targetHtmlPath = path.join(toolsDir, target.slug, 'index.html');
    if (!fs.existsSync(targetHtmlPath)) {
      warn(t.id + ' → ' + chain.id + ': missing target page');
      continue;
    }
    const targetHtml = fs.readFileSync(targetHtmlPath, 'utf8');

    let destIds = [];
    if (chain.map && typeof chain.map === 'object') {
      destIds = Object.keys(chain.map);
    } else if (chain.toField) {
      destIds = [chain.toField];
    } else if (target.primaryInputId) {
      destIds = [target.primaryInputId];
    }

    for (const dest of destIds) {
      if (!htmlHasId(targetHtml, dest)) {
        fail(
          t.id +
            ' → ' +
            chain.id +
            ': destination field "' +
            dest +
            '" not found in ' +
            target.slug +
            '/index.html'
        );
      }
    }
  }
}

// Registry drift: re-emit to a temp string and compare (if files exist)
try {
  const { tools: toolsForEmit } = require('./toolsConfig');
  const clientTools = toolsForEmit.map((t) => ({
    id: t.id,
    slug: t.slug,
    title: t.title,
    chainsTo: (t.chainsTo || []).map((c) => ({
      id: c.id,
      label: c.label,
      toField: c.toField || null,
      map: c.map || null,
    })),
    shareKind: t.shareKind == null ? null : t.shareKind,
    offline: !!t.offline,
    persistPolicy: t.persistPolicy || null,
    shareRequiresConfirm: !!t.shareRequiresConfirm,
    primaryInputId: t.primaryInputId || null,
    primaryOutputId: t.primaryOutputId || null,
  }));
  const expected =
    '// AUTO-GENERATED by scripts/emit-tools-registry.js — do not edit by hand\n' +
    'window.CSToolsRegistry = ' +
    JSON.stringify({ tools: clientTools }, null, 2) +
    ';\n';

  for (const rel of [
    'content-site/tools/shared/tools-registry.js',
    'public/tools/shared/tools-registry.js',
  ]) {
    const p = path.join(root, rel);
    if (!fs.existsSync(p)) {
      warn('registry missing (run npm run emit:registry): ' + rel);
      continue;
    }
    const actual = fs.readFileSync(p, 'utf8');
    if (actual !== expected) {
      fail('registry out of date: ' + rel + ' (run npm run emit:registry)');
    }
  }
} catch (e) {
  warn('registry drift check skipped: ' + e.message);
}

console.log('--- seo-assert summary ---');
console.log('tools:', tools.length);
console.log('errors:', errors);
console.log('warnings:', warnings);

if (errors > 0) {
  process.exit(1);
}
console.log('seo-assert: ok');
